# This is a full example of how to run the echo actor exposed with an HTTP server. Using this
# example requires you to have WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm. You
# can deploy this example with two simple commands:
#
# `wash app put wadm.yaml`
# `wash app deploy echo 0.0.1`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: game_logic
  annotations:
    version: v0.0.1
    description: "wasmCloud game_logic Example"
spec:
  components:
    - name: game_logic
      type: actor
      properties:
        image: registry:5000/v2/game_logic:0.1.0
      traits:
        - type: linkdef
          properties:
            target: nats
            values:
              SUBSCRIPTION: AAA.client_handler.>
              URI: nats://nats:4222
        - type: spreadscaler
          properties:
            replicas: 1
    - name: nats
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.15.0
        contract: wasmcloud:httpserver
      traits:
        - type: spreadscaler
          properties:
            replicas: 1