FROM golang:1.20.2
RUN mkdir /ra_server
COPY ./firefox /ra_server/firefox
COPY ./go /ra_server/go
WORKDIR /ra_server/go
# ENV ABSOLUTE_PATH=/ra_server
RUN go mod tidy
ENTRYPOINT [ "go","run","main.go" ]